# Generated by Django 5.2.3 on 2025-06-26 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(blank=True, help_text='Job posting that led to the match', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobposting')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match',
                'ordering': ['-matched_on'],
                'indexes': [models.Index(fields=['user_1', 'user_2'], name='idx_match_users'), models.Index(fields=['user_1', 'matched_on'], name='idx_match_user1'), models.Index(fields=['user_2', 'matched_on'], name='idx_match_user2')],
                'constraints': [models.UniqueConstraint(fields=('user_1', 'user_2', 'job_post'), name='unique_match'), models.CheckConstraint(condition=models.Q(('user_1__lt', models.F('user_2'))), name='ordered_users')],
            },
        ),
        migrations.CreateModel(
            name='SwipeActions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swipe_type', models.CharField(choices=[('profile', 'Profile Swipe'), ('job', 'Job Swipe')], default='profile', help_text='Type of swipe: profile or job', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_post', models.ForeignKey(blank=True, help_text='Job posting context (for job swipes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='jobs.jobposting')),
                ('swiped_on', models.ForeignKey(help_text='User who was swiped on (for profile swipes)', on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipe_actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['swiped_on', 'timestamp'], name='idx_swipe_swiped_on'), models.Index(fields=['swiper', 'job_post'], name='idx_swipe_swiper'), models.Index(fields=['timestamp'], name='idx_swipe_timestamp')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('swipe_type', 'profile')), fields=('swiper', 'swiped_on'), name='unique_profile_swipe'), models.UniqueConstraint(condition=models.Q(('swipe_type', 'job')), fields=('swiper', 'job_post'), name='unique_job_swipe')],
            },
        ),
    ]
