# Generated by Django 5.2.3 on 2025-06-29 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_user', models.ForeignKey(help_text='User whose profile was bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who bookmarked the profile', on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_bookmark',
                'ordering': ['-saved_on'],
                'indexes': [models.Index(fields=['user', 'saved_on'], name='idx_bookmark_user')],
                'unique_together': {('user', 'bookmarked_user')},
            },
        ),
    ]
