# Generated by Django 5.2.3 on 2025-06-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_profilebookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilebookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profilebookmark',
            name='bookmarked_user',
        ),
        migrations.RemoveField(
            model_name='profilebookmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wishlisted_user',
            field=models.ForeignKey(blank=True, help_text='User profile that was wishlisted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='job_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='jobs.jobposting'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.CheckConstraint(condition=models.Q(('job_post__isnull', False), ('wishlisted_user__isnull', False), _connector='OR'), name='wishlist_has_job_or_user'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.CheckConstraint(condition=models.Q(('job_post__isnull', False), ('wishlisted_user__isnull', False), _negated=True), name='wishlist_not_both_job_and_user'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('job_post__isnull', False)), fields=('user', 'job_post'), name='unique_user_job_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('wishlisted_user__isnull', False)), fields=('user', 'wishlisted_user'), name='unique_user_profile_wishlist'),
        ),
        migrations.DeleteModel(
            name='ProfileBookmark',
        ),
    ]
